sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_4122bd6fb57e_key -iv $encrypted_4122bd6fb57e_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- docker build -t edwolb/docker-react -f Dockerfile.dev .
script:
- docker run edwolb/docker-react npm run test -- --coverage
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: docker-react-1742782984
  default: true
  on:
    all_branches: true
